import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
    index("./routes/index/page.tsx"),
    route("report", "./routes/report/page.tsx"),
    route("report/session/:sessionId", "./routes/report/[sessionId]/page.tsx"),
    route("report/details/:id", "./routes/report/[id]/page.tsx"),
    route("admin/login", "./routes/admin/login/page.tsx"),
    route("admin/dashboard", "./routes/admin/dashboard/page.tsx"),
    route("admin/reports", "./routes/admin/reports/page.tsx"),
    route("admin/review", "./routes/admin/review/page.tsx"),
    route("admin/escalations", "./routes/admin/escalations/page.tsx"),
    route("admin/audit-logs", "./routes/admin/audit-logs/page.tsx"),
    route("admin/users", "./routes/admin/users/page.tsx"),
    route("api/v1/admin/me", "./routes/api/v1/admin/me/route.ts"),
    route("api/v1/admin/logout", "./routes/api/v1/admin/logout/route.ts"),
    route("api/v1/violations/analyze", "./routes/api/v1/violations/analyze/route.ts"),
    route("api/v1/violations/escalated", "./routes/api/v1/violations/escalated/route.ts"),
    route("api/v1/violations/sessions", "./routes/api/v1/violations/sessions/route.ts"),
    route("api/v1/violations/sessions/:sessionId", "./routes/api/v1/violations/sessions/[sessionId]/route.ts"),
    route("api/v1/admin/reports", "./routes/api/v1/admin/reports/route.ts"),
    route("api/v1/admin/reports/:id", "./routes/api/v1/admin/reports/[id]/route.ts"),
    route("api/v1/admin/reports/pending", "./routes/api/v1/admin/reports/pending/route.ts"),
    route("api/v1/admin/reports/:id/approve", "./routes/api/v1/admin/reports/[id]/approve/route.ts"),
    route("api/v1/admin/reports/:id/reject", "./routes/api/v1/admin/reports/[id]/reject/route.ts"),
    route("api/v1/admin/reports/:id/escalate", "./routes/api/v1/admin/reports/[id]/escalate/route.ts"),
    route("api/v1/admin/escalations", "./routes/api/v1/admin/escalations/route.ts"),
    route("api/v1/admin/escalations/:id/resolve", "./routes/api/v1/admin/escalations/[id]/resolve/route.ts"),
    route("api/v1/admin/audit-logs", "./routes/api/v1/admin/audit-logs/route.ts"),
    route("api/v1/admin/users", "./routes/api/v1/admin/users/route.ts"),
    route("api/v1/admin/users/:id", "./routes/api/v1/admin/users/[id]/route.ts"),
] satisfies RouteConfig;
